//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortfolioProjectNight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        public int SkillsId { get; set; }
        public string SkillsName { get; set; }
        public Nullable<byte> Rate { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
